
export type CarData = Record<string, Record<string, string[]>>;

export const carData: CarData = {
  Abarth: { "595": [], "695": [] },
  "Alfa Romeo": {
    Giulia: [],
    Stelvio: [],
    Tonale: [],
  },
  Alpine: { A110: [] },
  Audi: {
    A1: [],
    A3: [],
    A4: [],
    A5: [],
    A6: [],
    A7: [],
    A8: [],
    Q2: [],
    Q3: [],
    Q4: [],
    Q5: [],
    Q7: [],
    Q8: [],
    "e-tron": [],
    "e-tron GT": [],
  },
  BMW: {
    "1-Serie": [],
    "2-Serie": [],
    "3-Serie": [],
    "4-Serie": [],
    "5-Serie": [],
    "7-Serie": [],
    "8-Serie": [],
    X1: [],
    X2: [],
    X3: [],
    X4: [],
    X5: [],
    X6: [],
    X7: [],
    Z4: [],
    iX1: [],
    iX2: [],
    iX3: [],
    i4: [],
    i5: [],
    i7: [],
    iX: [],
  },
  Citroën: {
    Berlingo: ["M", "XL"],
    Jumpy: ["M", "XL"],
    Jumper: ["L2H2", "L3H2"],
    C3: [],
    "C3 Aircross": [],
    C4: [],
    "C4 X": [],
    C5: [],
    "C5 Aircross": [],
    "ë-C4": [],
    "ë-Jumpy": [],
  },
  Cupra: {
    Born: [],
    Formentor: [],
    Leon: [],
    Ateca: [],
  },
  Dacia: {
    Duster: [],
    Jogger: [],
    Sandero: [],
    Spring: [],
  },
  "DS Automobiles": {
    DS3: [],
    DS4: [],
    DS7: [],
    DS9: [],
  },
  Ferrari: {
    "296 GTB": [],
    "812 Superfast": [],
    Roma: [],
    Purosangue: [],
  },
  Fiat: {
    "500": [],
    "500e": [],
    "500X": [],
    Panda: [],
    Tipo: [],
    Ducato: ["L2H2", "L3H2", "E-Tech"],
    Scudo: [],
    Doblò: [],
  },
  Ford: {
    Transit: ["L2H2", "L3H2", "L4H3"],
    "Transit Custom": ["Limited", "Trend", "Sport"],
    "Transit Connect": [],
    "Transit Courier": [],
    Ranger: ["Wildtrak", "Raptor", "XLT"],
    Puma: [],
    Kuga: [],
    Focus: [],
    Fiesta: [],
    "Mustang Mach-E": [],
    Explorer: [],
  },
  Honda: {
    "Civic": [],
    "HR-V": [],
    "CR-V": [],
    "Jazz": [],
    "e:Ny1": [],
  },
  Hyundai: {
    i10: [],
    i20: [],
    i30: [],
    Kona: [],
    Tucson: [],
    "Santa Fe": [],
    "Ioniq 5": [],
    "Ioniq 6": [],
  },
  Jaguar: {
    "F-Pace": [],
    "E-Pace": [],
    "I-Pace": [],
    XE: [],
    XF: [],
  },
  Jeep: {
    Avenger: [],
    Renegade: [],
    Compass: [],
    Wrangler: [],
    "Grand Cherokee": [],
  },
  Kia: {
    Picanto: [],
    Rio: [],
    Ceed: [],
    Niro: [],
    Sportage: [],
    Sorento: [],
    Stonic: [],
    EV6: [],
    EV9: [],
  },
  "Land Rover": {
    "Defender": [],
    "Discovery": [],
    "Discovery Sport": [],
    "Range Rover": [],
    "Range Rover Sport": [],
    "Range Rover Velar": [],
    "Range Rover Evoque": [],
  },
  Lexus: {
    UX: [],
    NX: [],
    RX: [],
    ES: [],
    RZ: [],
  },
  Maserati: {
    Grecale: [],
    Levante: [],
    Ghibli: [],
    Quattroporte: [],
  },
  Mazda: {
    "2": [],
    "3": [],
    "CX-30": [],
    "CX-5": [],
    "CX-60": [],
    "MX-30": [],
    "MX-5": [],
  },
  "Mercedes-Benz": {
    Sprinter: ["314 CDI", "316 CDI", "319 CDI", "516 CDI", "519 CDI"],
    Vito: ["110 CDI", "114 CDI", "116 CDI", "119 CDI", "e-Vito"],
    Citan: ["108 CDI", "109 CDI", "111 CDI", "e-Citan"],
    "A-Klasse": [],
    "C-Klasse": [],
    "E-Klasse": [],
    "S-Klasse": [],
    GLA: [],
    GLB: [],
    GLC: [],
    GLE: [],
    GLS: [],
    EQA: [],
    EQB: [],
    EQC: [],
    EQE: [],
    EQS: [],
  },
  MG: {
    "4": [],
    "5": [],
    ZS: [],
    EHS: [],
    "Marvel R": [],
  },
  "Mini": {
    "3-deurs": [],
    "5-deurs": [],
    Cabrio: [],
    Clubman: [],
    Countryman: [],
  },
  Mitsubishi: {
    "Space Star": [],
    Colt: [],
    ASX: [],
    "Eclipse Cross": [],
  },
  Nissan: {
    Juke: [],
    Qashqai: [],
    "X-Trail": [],
    Ariya: [],
    Leaf: [],
    Townstar: [],
    Primastar: ["Acenta", "Tekna"],
    Interstar: [],
  },
  Opel: {
    Corsa: [],
    Astra: [],
    Mokka: [],
    "Crossland": [],
    "Grandland": [],
    Combo: [],
    Vivaro: ["Edition", "Elegance"],
    Movano: ["L2H2", "L3H2"],
  },
  Peugeot: {
    "208": [],
    "308": [],
    "408": [],
    "508": [],
    "2008": [],
    "3008": [],
    "5008": [],
    Partner: ["Asphalt", "Grip"],
    Expert: ["Standard", "Long"],
    Boxer: ["L2H2", "L3H2"],
  },
  Polestar: {
    "2": [],
    "3": [],
    "4": [],
  },
  Porsche: {
    "911": [],
    "718 Boxster": [],
    "718 Cayman": [],
    Taycan: [],
    Panamera: [],
    Macan: [],
    Cayenne: [],
  },
  Renault: {
    Clio: [],
    Captur: [],
    Megane: [],
    Austral: [],
    Arkana: [],
    Espace: [],
    Trafic: ["L1H1", "L2H1"],
    Master: ["L2H2", "L3H2", "E-Tech"],
    Kangoo: [],
  },
  Seat: {
    Ibiza: [],
    Leon: [],
    Arona: [],
    Ateca: [],
    Tarraco: [],
  },
  Skoda: {
    Fabia: [],
    Scala: [],
    Octavia: [],
    Superb: [],
    Kamiq: [],
    Karoq: [],
    Kodiaq: [],
    Enyaq: [],
  },
  Smart: {
    "#1": [],
    "#3": [],
  },
  Subaru: {
    Impreza: [],
    XV: [],
    Forester: [],
    Outback: [],
  },
  Suzuki: {
    Ignis: [],
    Swift: [],
    "S-Cross": [],
    Vitara: [],
    Swace: [],
  },
  Tesla: {
    "Model 3": [],
    "Model Y": [],
    "Model S": [],
    "Model X": [],
  },
  Toyota: {
    Aygo: [],
    Yaris: [],
    "Yaris Cross": [],
    Corolla: [],
    "C-HR": [],
    "RAV4": [],
    Highlander: [],
    "bZ4X": [],
    Proace: ["Compact", "Worker", "Long Worker"],
    "Proace City": [],
  },
  Volkswagen: {
    Transporter: ["T6.1", "T7"],
    Caddy: ["Cargo", "Cargo Maxi"],
    Crafter: ["L2H2", "L3H3", "L4H3"],
    "ID. Buzz": ["Cargo"],
    "Polo": [],
    "Golf": [],
    "Taigo": [],
    "T-Cross": [],
    "T-Roc": [],
    "Tiguan": [],
    "Passat": [],
    "Arteon": [],
    "ID.3": [],
    "ID.4": [],
    "ID.5": [],
    "ID.7": [],
  },
  Volvo: {
    S60: [],
    V60: [],
    S90: [],
    V90: [],
    XC40: [],
    C40: [],
    XC60: [],
    XC90: [],
    EX30: [],
    EX90: [],
  },
};
