export const gemeenten = [
  "Aa en Hunze", "Aalsmeer", "Aalten", "Achtkarspelen", "Alblasserdam", "Albrandswaard", 
  "Alkmaar", "Almelo", "Almere", "Alphen aan den Rijn", "Alphen-Chaam", "Altena", 
  "Amersfoort", "Amstelveen", "Amsterdam", "Apeldoorn", "Appingedam", "Arnhem", 
  "Assen", "Asten", "Baarle-Nassau", "Baarn", "Barendrecht", "Barneveld", "Beek", 
  "Beekdaelen", "Beemster", "Beesel", "Berg en Dal", "Bergeijk", "Bergen (L.)", 
  "Bergen (NH.)", "Bergen op Zoom", "Berkelland", "Bernheze", "Best", "Beuningen", 
  "Beverwijk", "Bladel", "Blaricum", "Bloemendaal", "Bodegraven-Reeuwijk", "Boekel", 
  "Bolsward", "Borger-Odoorn", "Borne", "Borsele", "Boxmeer", "Boxtel", "Breda", 
  "Briele", "Bronckhorst", "Brummen", "Brunssum", "Bunnik", "Bunschoten", "Buren", 
  "Capelle aan den IJssel", "Castricum", "Coevorden", "Cranendonck", "Cuijk", 
  "Culemborg", "Dalfsen", "Dantumadiel", "De Bilt", "De Friese Meren", "De Fryske Marren", 
  "De Marne", "De Ronde Venen", "De Wolden", "Delft", "Delfzijl", "Deurne", "Deventer", 
  "Diemen", "Dinkelland", "Doesburg", "Doetinchem", "Dongen", "Dordrecht", "Drechterland", 
  "Drimmelen", "Dronten", "Druten", "Duiven", "Echt-Susteren", "Edam-Volendam", "Ede", 
  "Eemnes", "Eemsdelta", "Eersel", "Eijsden-Margraten", "Eindhoven", "Elburg", "Emmen", 
  "Enkhuizen", "Enschede", "Epe", "Ermelo", "Etten-Leur", "Ferwerderadiel", "Franekeradeel",
  "Geertruidenberg", "Geldrop-Mierlo", "Gemert-Bakel", "Gennep", "Gilze en Rijen", 
  "Goeree-Overflakkee", "Goes", "Gooise Meren", "Gorinchem", "Gouda", "Grave", "Groningen", 
  "Gulpen-Wittem", "Haaksbergen", "Haaren", "Haarlem", "Haarlemmermeer", "Halderberge", 
  "Hardenberg", "Harderwijk", "Hardinxveld-Giessendam", "Harlingen", "Hattem", "Heemskerk", 
  "Heemstede", "Heerde", "Heerenveen", "Heerhugowaard", "Heerlen", "Heeze-Leende", 
  "Heiloo", "Hellendoorn", "Hellevoetsluis", "Helmond", "Hendrik-Ido-Ambacht", "Hengelo", 
  "Het Hogeland", "Heumen", "Heusden", "Hillegom", "Hilvarenbeek", "Hilversum", 
  "Hoeksche Waard", "Hof van Twente", "Hollands Kroon", "Hoogeveen", "Hoorn", "Horst aan de Maas", 
  "Houten", "Huizen", "Hulst", "IJsselstein", "Kaag en Braassem", "Kampen", "Kapelle", 
  "Katwijk", "Kerkrade", "Koggenland", "Krimpen aan den IJssel", "Krimpenerwaard", "Laarbeek", 
  "Landerd", "Land van Cuijk", "Landsmeer", "Langedijk", "Lansingerland", "Laren", "Leeuwarden", 
  "Leiden", "Leiderdorp", "Leidschendam-Voorburg", "Lelystad", "Leudal", "Leusden", 
  "Lingewaard", "Lisse", "Littenseradiel", "Lochem", "Loon op Zand", "Lopik", "Loppersum", 
  "Losser", "Maasdriel", "Maasgouw", "Maassluis", "Maastricht", "Medemblik", "Meerssen", 
  "Meierijstad", "Meppel", "Middelburg", "Midden-Delfland", "Midden-Drenthe", 
  "Midden-Groningen", "Mill en Sint Hubert", "Moerdijk", "Molenlanden", "Montferland", 
  "Montfoort", "Mook en Middelaar", "Neder-Betuwe", "Nederweert", "Nieuwegein", "Nieuwkoop", 
  "Nijkerk", "Nijmegen", "Nissewaard", "Noardeast-Fryslân", "Noord-Beveland", "Noordenveld", 
  "Noordoostpolder", "Nuenen, Gerwen en Nederwetten", "Nunspeet", "Oegstgeest", "Oirschot", 
  "Oisterwijk", "Oldambt", "Oldebroek", "Oldenzaal", "Olst-Wijhe", "Ommen", "Oost Gelre", 
  "Oosterhout", "Ooststellingwerf", "Opmeer", "Opsterland", "Oss", "Oud-Beijerland", 
  "Oude IJsselstreek", "Ouder-Amstel", "Oudewater", "Overbetuwe", "Papendrecht", "Peel en Maas", 
  "Pekela", "Pijnacker-Nootdorp", "Purmerend", "Putten", "Raalte", "Radolfzell am Bodensee",
  "Reimerswaal", "Renswoude", "Reusel-De Mierden", "Rheden", "Rhenen", "Ridderkerk", "Rijswijk", 
  "Roerdalen", "Roermond", "Roosendaal", "Rotterdam", "Rozendaal", "Rucphen", "Schagen", 
  "Scheveningen", "Schiedam", "Schiermonnikoog", "Schouwen-Duiveland", "'s-Gravenhage", 
  "'s-Hertogenbosch", "Simpelveld", "Sint Anthonis", "Sint-Michielsgestel", "Sittard-Geleen", 
  "Sliedrecht", "Sluis", "Smallingerland", "Soest", "Someren", "Son en Breugel", "Stadskanaal", 
  "Staphorst", "Stede Broec", "Steenbergen", "Steenwijkerland", "Stein", "Stichtse Vecht", 
  "Súdwest-Fryslân", "Terneuzen", "Terschelling", "Texel", "Teylingen", "Tholen", "Tiel", 
  "Tilburg", "Tubbergen", "Twenterand", "Tynaarlo", "Tytsjerksteradiel", "Uden", "Uitgeest", 
  "Uithoorn", "Urk", "Utrecht", "Utrechtse Heuvelrug", "Vaals", "Valkenburg aan de Geul", 
  "Valkenswaard", "Veendam", "Veenendaal", "Veere", "Veldhoven", "Venlo", "Venray", 
  "Vijfheerenlanden", "Vlaardingen", "Vlieland", "Vlissingen", "Voerendaal", "Voorschoten", 
  "Voorst", "Vught", "Waalre", "Waalwijk", "Waddinxveen", "Wageningen", "Wassenaar", 
  "Waterland", "Weert", "West Betuwe", "West Maas en Waal", "Westerkwartier", "Westerveld", 
  "Westervoort", "Westerwolde", "Westland", "Weststellingwerf", "Westvoorne", "Wierden", 
  "Wieringermeer", "Wijchen", "Wijdemeren", "Wijk bij Duurstede", "Winsum", "Winterswijk", 
  "Woensdrecht", "Woerden", "Wormerland", "Woudenberg", "Zaanstad", "Zaltbommel", "Zandvoort", 
  "Zederik", "Zeist", "Zevenaar", "Zoetermeer", "Zoeterwoude", "Zuidplas", "Zundert", 
  "Zutphen", "Zwartewaterland", "Zwijndrecht", "Zwolle"
];
